# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitBunker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.4'
  pod 'CryptoSwift'
  pod 'RichEditorView', :git => "https://github.com/cjwirth/RichEditorView.git", :branch => "master"

  # Pods for BitBunker

  target 'BitBunkerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitBunkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
